# ------------------------------------------------------------------------------
# Output
# Version: 1.0.0
# ------------------------------------------------------------------------------

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.aws_region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.eks_cluster_name
}

output "client_repository_url" {
  description = "exampleapp-client repository URL"
  value       = aws_ecr_repository.exampleapp-client.repository_url
}

output "server_repository_url" {
  description = "exampleapp-server repository URL"
  value       = aws_ecr_repository.exampleapp-server.repository_url
}
